version: "3.7"
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    ports:
      - "3416:80"
    restart: unless-stopped
    volumes:
      - data:/pb_data
      - public:/pb_public
      - migrations:/pb_migrations

  email-builder:
    build: .
    container_name: email-builder
    depends_on:
      - pocketbase
    ports:
      - "3417:3000"
    restart: unless-stopped
    environment:
      - POCKETBASE_URL=http://pocketbase # replace with an FQDN via an (SSL enabled for oAuth2) reverse proxy
      # - CALLBACK_URL=https://emailbuilder.mydomain.com/auth/callback/ # replace with the app url, keep "/auth/callback/" path

volumes:
  data:
  public:
  migrations: