version: "3.7"
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    ports:
      - "3416:80"
    restart: unless-stopped
    volumes:
      - data:/pb_data
      - public:/pb_public
      - migrations:/pb_migrations

  email-builder:
    build: .
    container_name: email-builder
    depends_on:
      - pocketbase
    ports:
      - "3417:3000"
    restart: unless-stopped
    environment:
      - ORIGIN=https://emailbuilder.mydomain.com # replace with an FQDN served by a reverse proxy
      - POCKETBASE_URL=https://emailbuilder.db.mydomain.com # replace with an FQDN served by a reverse proxy

volumes:
  data:
  public:
  migrations: